#!/bin/bash
if pgrep tint2 && pgrep polybar; then
	pkill tint2
	pkill polybar
	exit 1
else

	exec tint2 -c ~/.config/tint2/workspaces.tint2rc &
	exec tint2 -c ~/.config/tint2/clock.tint2rc &
	exec sh ~/.config/polybar/launch.sh&
fi
exit

