#!/bin/bash 
day_num="$(date +%u)"
if [$day_num -eq 1] 
then	day="Monday"
elif [$day_num -eq 2]
then	day="Tuesday"
elif [ $day_num -eq 3 ]
then	day="Wednesday"
elif [ $day_num -eq 4 ]
then	day="Thursday"
elif [ $day_num -eq 5 ]
then	day="Friday"
elif [ $day_num -eq 6 ]
then	day="Saturday"
else	day="Sunday"
fi
echo $day;
